# Generated by Django 4.1 on 2022-09-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('inn', models.IntegerField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('office', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=100)),
                ('store', models.BooleanField()),
                ('regional_store', models.BooleanField()),
                ('federal_store', models.BooleanField()),
                ('online_store', models.BooleanField()),
                ('car_service', models.BooleanField()),
                ('other', models.CharField(blank=True, max_length=100)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.category')),
            ],
        ),
    ]
